application: demo
version: alpha-001
port: 1025

handlers:
  - url: '/doc/{year}/{id}'
    script: sample/doc.groovy
    http_headers:
      X-Foo-Header: foo
      X-Bar-Header: bar value

  - url: /sample/param
    script: sample/param.groovy

filters:
  - url_pattern: /admin/*
    script: filter.groovy

listeners:
  - start: app_start.groovy
    stop: app_stop.groovy

error_handlers:
  - file: default_error.html
  
  - error_code: 404
    file: over_quota.html

index_pages: 
  - index.html
  - index.htm
  - index.groovy

charset_encoding: utf-8
file_encoding: utf-8

thread_pool:
    max_threads: 80
    min_threads: 5
    idle_timeout: 0